#!/usr/bin/env zsh

wenv_def() {
    WENV_DIR="/home/grish/.ipfs-private"
    WENV_DEPS=()
    WENV_PROJECT=''
    WENV_TASK=''
    WENV_EXTENSIONS=('c')

    startup_wenv() {}
    shutdown_wenv() {}
    bootstrap_wenv() {}
}

# for c extension
# declare -Ag wenv_dirs=()

# for edit extension
# declare -Ag wenv_files=()# # useful command sequences

# ## remove all data from local ipfs datastore
# $ ipfs pin ls --type=recursive | cut -d' ' -f1 | xargs -n1 ipfs pin rm
# $ ipfs repo gc

export IPFS_BIN=/usr/bin/ipfs

declare -Ag ipfs_path
ipfs_path[public]="$HOME/.ipfs-public"
ipfs_path[private]="$HOME/.ipfs-private"

set_ipfs_path() {
    case "$1" in
        'public'|'private')
            export IPFS_PATH="${ipfs_path[$1]}"
            ;;
        *) # default to private ipfs node
            export IPFS_PATH="${ipfs_path[private]}"
            ;;
    esac
}
alias sip=set_ipfs_path

_set_ipfs_path() {
    COMPREPLY=()
    complete +o default

    local word="${COMP_WORDS[COMP_CWORD]}"
    local prev="${COMP_WORDS[COMP_CWORD-1]}"

    if (( COMP_CWORD == 1 )) && [[ ${word} == -* ]]; then
        COMPREPLY=( $(compgen -W "-r -h" -- ${word}) )
    elif (( COMP_CWORD == 1 )) || { ((COMP_CWORD == 2 )) && [[ ${prev} == -* ]]; }; then
        local opts="${(k)ipfs_path[@]}"
        COMPREPLY=( $(compgen -W "${opts}" -- ${word}) )
    fi
}
complete -F _set_ipfs_path set_ipfs_path

sip private

ipfs() {
    case "$1" in
        'public'|'private')
            local cfg=$1 && shift
            IPFS_PATH=${ipfs_path[$cfg]} $IPFS_BIN $@
            ;;
        *) # default to private ipfs node
            IPFS_PATH=${ipfs_path[private]} $IPFS_BIN $@
            ;;
    esac
}
