#!/usr/bin/env zsh

wenv_def() {
    WENV_DIR="/home/grish/.ipfs"
    WENV_DEPS=()
    WENV_PROJECT=''
    WENV_TASK=''
    WENV_EXTENSIONS=('c')

    startup_wenv() {}
    shutdown_wenv() {}
    bootstrap_wenv() {}
}

export IPFS_BIN=/usr/bin/ipfs

declare -Ag ipfs_path
ipfs_path[public]="$WENV_DIR/public"
ipfs_path[private]="$WENV_DIR/private"

ipfs() {
    case "$1" in
        'public'|'private')
            local cfg=$1 && shift
            IPFS_PATH=${ipfs_path[$cfg]} $IPFS_BIN $@
            ;;
        *) # default to public ipfs node
            IPFS_PATH=${ipfs_path[public]} $IPFS_BIN $@
            ;;
    esac
}

# for c extension
# declare -Ag wenv_dirs=()

# for edit extension
# declare -Ag wenv_files=()
