#!/usr/bin/env zsh

wenv_def() {
    WENV_DIR="$SCRATCH/ipfs/testground-home/plans/testbed/testbed"
    WENV_DEPS=()
    WENV_PROJECT=''
    WENV_TASK=''
    WENV_EXTENSIONS=('c' 'kak_session')

    startup_wenv() {
        sudo systemctl start docker
    }
    shutdown_wenv() {
        sudo systemctl stop docker
    }
    bootstrap_wenv() {}
}

export TESTGROUND_HOME="$SCRATCH/ipfs/testground-home"

# for c extension
declare -Ag wenv_dirs

# tests + source code
wenv_dirs[home]="$TESTGROUND_HOME"
wenv_dirs[ipfs-test-plans]="$SRC/ipfs/test-plans"
wenv_dirs[bitswap]="$SRC/ipfs/go-bitswap"
wenv_dirs[beyond-bitswap]="$SRC/ipfs/beyond-bitswap"
wenv_dirs[peertaskqueue]="$SRC/ipfs/go-peertaskqueue"
wenv_dirs[results]="${wenv_dirs[home]}/data/outputs/local_docker/bitswap-tuning"

# thesis
wenv_dirs[thesis]="$SCRATCH/thesis"
wenv_dirs[notes]="$SCRATCH/thesis/notes"
wenv_dirs[plots]="$SCRATCH/thesis/plots"

# testground
wenv_dirs[src]="$SRC/ipfs/testground"
wenv_dirs[sdk]="$SRC/ipfs/testground-sdk-go"

unalias c
c() {
    case "$1" in
        'results')
            cd $wenv_dirs[results]/$2
            ;;
        *)
            __c $@
            ;;
    esac
}

_run() {
    local branch="$1" && shift
    [[ -z "$branch" ]] && branch=master

    testground run single --plan=bitswap-tuning --testcase=transfer --builder=docker:go --runner=local:docker \
        --dep github.com/ipfs/go-bitswap=github.com/dgrisham/go-bitswap@$branch \
        --dep github.com/ipfs/go-peertaskqueue=github.com/dgrisham/go-peertaskqueue@$branch \
        --test-param "run_prefix=$branch" $@
}

run_master() {
    run 'master'
}

run_peer_weights() {
    run 'peer-weights'
}

# for edit extension
# declare -Ag wenv_files=()
