#!/bin/zsh

wenv_def() {
    typeset -Ag WENV_CONSTS
    WENV_DIR="/home/grish/work/research/accountability"
    WENV_DEPS=()
    WENV_NAME='accountability'
    WENV_BRANCH=''
    WENV_TASK=''
    startup_wenv() {
        edit_week
    }
    shutdown_wenv() { }
}
