#!/bin/zsh

wenv_def() {
    typeset -Ag WENV_CONSTS
    WENV_DIR=""
    WENV_DEPS=()
    WENV_NAME='analytical-strategy-analysis'
    WENV_BRANCH='master'
    WENV_TASK=''
    startup_wenv() { }
    shutdown_wenv() { }
}
