#!/bin/zsh

wenv_def() {
    WENV_DIR="/home/grish/scratch/webdev/apollo-angular-app/"
    WENV_DEPS=()
    WENV_PROJECT='webdev'
    WENV_BRANCH='master'
    startup_wenv() { }
    shutdown_wenv() { }
}
