#!/bin/zsh

wenv_def() {
    WENV_DIR="/home/grish/scratch/ipfs/specs/bitswap"
    WENV_DEPS=()
    WENV_PROJECT='bitswap-spec'
    WENV_BRANCH='bitswap/spec-update'
    WENV_TASK=78
    startup_wenv() {
        wenv_tmux_layout 'dev' 'wenv task'
        [[ ! $(pwd) = "$WENV_DIR" ]] && wenv c
        yes | mdImport README.md
        tmux send-keys 'kak README.md' 'Enter' '/continue' 'Enter'
    }
    shutdown_wenv() {
        [[ ! $(pwd) = "$WENV_DIR" ]] && wenv c
        yes | mdExport README.md
    }
}
