#!/bin/zsh

wenv_def() {
    WENV_DIR="$HOME/src/bitswap-diagram"
    WENV_DEPS=()
    WENV_PROJECT=''
    WENV_BRANCH='master'
    WENV_TASK=''
    WENV_GITDIR=""

    startup_wenv() { }
    shutdown_wenv() { }
}
