#!/bin/zsh

wenv_def() {
    WENV_DIR="/home/grish/scratch/blog"
    WENV_DEPS=()
    WENV_PROJECT=''
    WENV_EXTENSIONS=('c' 'edit')

    bootstrap_wenv() {}
    startup_wenv() {
        sudo systemctl start httpd mariadb vsftpd
    }
    shutdown_wenv() {
        sudo systemctl stop httpd mariadb vsftpd
    }
}

restart() {
    sudo systemctl restart httpd mariadb vsftpd
}

declare -Ag wenv_dirs=(
    ['wordpress']='/srv/http/wordpress'
    ['ftp']='/srv/ftp'
)

declare -Ag wenv_files=(
    ['apache']='/etc/httpd/conf/httpd.conf'
    ['server']='${wenv_files[apache]}'
    ['notes']="$SCRATCH/blog/notes.md"
)
