#!/bin/zsh

wenv_def() {
    WENV_DIR="/home/grish/src/bootstrap"
    WENV_DEPS=()
    WENV_PROJECT=''
    WENV_BRANCH=''
    WENV_TASK=''
    WENV_GITDIR=""

    startup_wenv() {}
    shutdown_wenv() {}
}
