#!/bin/zsh

wenv_def() {
    WENV_DIR="/home/grish/src/haskell-calculator-0.1.0.0"
    WENV_DEPS=()
    WENV_PROJECT='haskell-calculator'
    unset WENV_BRANCH
    startup_wenv() { }
    shutdown_wenv() { }
}
