#!/usr/bin/env zsh

wenv_def() {
    WENV_DIR="$GOPATH/src/github.com/ipfs/ipfs-cluster"
    WENV_DEPS=('ipfs' 'iptl')
    WENV_PROJECT='free-space-allocation-metric'
    WENV_BRANCH='feat/free-space-allocation-metric'

    startup_wenv() { }
    shutdown_wenv() { }
}
