#!/usr/bin/env zsh

wenv_def() {
    WENV_DIR="$GOPATH/src/github.com/ipfs/ipfs-cluster"
    WENV_DEPS=('ipfs' 'iptl' 'cluster')
    WENV_PROJECT='cluster-basic-auth'
    WENV_BRANCH='feat/api-basic-auth'
    WENV_TASK='76'

    startup_wenv() { }
    shutdown_wenv() { }
}
