#!/bin/zsh

wenv_def() {
    WENV_DIR="/home/grish/scratch/docutils/docutils/docutils"
    WENV_DEPS=()
    WENV_PROJECT=''
    WENV_BRANCH='master'
    WENV_TASK=''
    WENV_GITDIR=""

    startup_wenv() {
        wenv_tmux_split h "$EDITOR $BIN/rst2latex_mod"
    }
    shutdown_wenv() { }
}
