#!/bin/zsh

wenv_setup() {
    WENV_DIR="/home/grish/scratch/docutils/docutils/docutils"
    WENV_DEPS=()
    WENV_PROJECT=''
    WENV_BRANCH='master'
    WENV_TASK=''
    WENV_GITDIR=""

    wenv_init() {
        wenv_tmux_split h "$EDITOR $BIN/rst2latex_mod"
    }
    wenv_shutdown() { }
}
