#!/bin/zsh

wenv_def() {
    WENV_DIR="/home/grish/scratch/go"
    WENV_DEPS=()
    WENV_PROJECT=''
    WENV_BRANCH='master'
    WENV_TASK=''
    WENV_GITDIR=""

    startup_wenv() {
        wenv_tmux_layout devloop -w file main.go "'clear; go fmt ./... && go build -o main && ./main'"
        tmux rename-window src
        $EDITOR main.go
    }
    shutdown_wenv() { }
}
