#!/bin/zsh

wenv_def() {
    WENV_DIR="/home/grish/personal"
    WENV_DEPS=()
    WENV_PROJECT=''
    WENV_BRANCH=''
    startup_wenv() {
        [[ -z "$TMUX" ]] && return 1
        wenv_tmux_split h
        tmux send-keys 'kak goals.md' 'Enter'
    }
}
