#!/bin/zsh

wenv_def() {
    WENV_DIR="/home/grish/scratch/hello-world"
    WENV_DEPS=()
    WENV_PROJECT=''
    WENV_TASK=''

    startup_wenv() {}
    shutdown_wenv() {
        ech 2
    }
    bootstrap_wenv() {}
}

declare -Ag wenv_dirs=(
    ['dl']="$HOME/downloads"
    ['home']="$HOME"
)
declare -Ag wenv_files=(
    ['rst']='*.rst'
    ['bob']='bob'
    ['errywun']='bob jim jimbob'
)

c() {
    local flag_r=0
    while getopts ":r" opt; do
        case $opt in
            r) flag_r=1 ;;
        esac
    done
    shift $((OPTIND-1))

    input="$1"
    shift
    [ "${wenv_dirs[$input]+0}" ] || return 1
    cd "${wenv_dirs[$input]}"
    (( flag_r == 1 )) && tmux rename-window "$wname"
}
_c() {
    COMPREPLY=()
    complete +o default

    local word="${COMP_WORDS[COMP_CWORD]}"
    local prev="${COMP_WORDS[COMP_CWORD-1]}"

    if (( COMP_CWORD == 1 )) && [[ ${word} == -* ]]; then
        COMPREPLY=( $(compgen -W "-r" -- ${word}) )
    elif (( COMP_CWORD == 1 )) || { ((COMP_CWORD == 2 )) && [[ ${prev} == -* ]]; }; then
        local opts="${(k)wenv_dirs[@]}"
        COMPREPLY=( $(compgen -W "${opts}" -- ${word}) )
    fi
}
complete -F _c c

edit() {
    local flag_r=0
    while getopts ":r" opt; do
        case $opt in
            r) flag_r=1 ;;
        esac
    done
    shift $((OPTIND-1))

    input="$1"
    shift
    [ "${wenv_files[$input]+0}" ] || return 1
    (( flag_r == 1 )) && tmux rename-window "$wname"
    eval $EDITOR $@ "$WENV_DIR/${wenv_files[$input]}"
}
_edit() {
    COMPREPLY=()
    complete +o default

    local word="${COMP_WORDS[COMP_CWORD]}"
    local prev="${COMP_WORDS[COMP_CWORD-1]}"

    if (( COMP_CWORD == 1 )) && [[ ${word} == -* ]]; then
        COMPREPLY=( $(compgen -W "-r" -- ${word}) )
    elif (( COMP_CWORD == 1 )) || { ((COMP_CWORD == 2 )) && [[ ${prev} == -* ]]; }; then
        local opts="${(k)wenv_files[@]}"
        COMPREPLY=( $(compgen -W "${opts}" -- ${word}) )
    fi
}
complete -F _edit edit
