#!/usr/bin/env zsh

wenv_def() {
    WENV_DIR="/mnt/vm/dev/studio-manager"
    WENV_DEPS=('inspire-vagrant')
    WENV_PROJECT=''
    WENV_TASK=''
    WENV_EXTENSIONS=('c' 'edit')

    startup_wenv() {
        wenv start -d inspire-vagrant
        wenv cd inspire-vagrant
        until [[ -d "$WENV_DIR" ]]; do sleep 1; done
        wenv cd
    }
    shutdown_wenv() {}
    bootstrap_wenv() {}
}

# for c extension
declare -Ag wenv_dirs=(
    ['studio-api']="../studio_api"
    ['wiki']="$SRC/inspire/studio-manager.wiki"
    ['api']="$SRC/inspire/api-documentation"
)

# for edit extension
declare -Ag wenv_files=(
    ['api']="${wenv_dirs[api]}/reference/studio-manager/openapi.yaml"
)

reset_studio_db() {
    vagrant_run 'sudo su -l postgres -c "psql -f ~vagrant/dev/studio-manager/tables.sql && psql -f ~vagrant/dev/studio-manager/db-init.sql"'
}
alias rsd='reset_studio_db'
