#!/usr/bin/env zsh

wenv_def() {
    WENV_DIR="/mnt/vm/dev/video-dashboard"
    WENV_DEPS=('inspire-vagrant')
    WENV_PROJECT=''
    WENV_TASK=''
    WENV_EXTENSIONS=('nvm')

    startup_wenv() {
        wenv start -d inspire-vagrant
        wenv cd inspire-vagrant
        until [[ -d "$WENV_DIR" ]]; do sleep 1; done
        wenv cd
    }
    shutdown_wenv() {}
    bootstrap_wenv() {}
}

nvm use 11.8 >/dev/null 2>&1

# for c extension
# declare -Ag wenv_dirs=()

# for edit extension
# declare -Ag wenv_files=()
