#!/bin/zsh

wenv_setup() {
    WENV_DIR="/home/grish/work/kleros"
    WENV_DEPS=()
    WENV_PROJECT='kleros'
    unset WENV_BRANCH
    WENV_TASK=''
    WENV_GITDIR=""

    wenv_bootstrap() {}
    wenv_init() {}
    wenv_shutdown() {}
}
