#!/bin/zsh

wenv_def() {
    WENV_DIR="/home/grish/work/kleros"
    WENV_DEPS=()
    WENV_PROJECT='kleros'
    unset WENV_BRANCH
    WENV_TASK=''
    WENV_GITDIR=""

    bootstrap_wenv() {}
    startup_wenv() {}
    shutdown_wenv() {}
}
