#!/bin/zsh

wenv_def() {
    typeset -Ag WENV_CONSTS
    WENV_DIR="/home/grish/personal/jobs/kleros/prescreen"
    WENV_DEPS=('md')
    WENV_NAME='kleros'
    WENV_BRANCH='master'
    startup_wenv() {
        pdf ./questions.pdf &
        doc_dev 'write_up.md'
    }
    shutdown_wenv() { }
}
