#!/bin/zsh

wenv_setup() {
    WENV_DIR="/home/grish/scratch/mopidy/mopidy-beets"
    WENV_DEPS=()
    WENV_PROJECT=''
    WENV_BRANCH='master'
    WENV_TASK=''
    WENV_GITDIR=""

    wenv_init() { }
    wenv_shutdown() { }
}
