#!/bin/zsh

wenv_def() {
    WENV_DIR="/home/grish/scratch/mopidy/mopidy-beets"
    WENV_DEPS=()
    WENV_PROJECT=''
    WENV_BRANCH='master'
    WENV_TASK=''
    WENV_GITDIR=""

    startup_wenv() { }
    shutdown_wenv() { }
}
