#!/bin/zsh

wenv_def() {
    WENV_DIR="/home/grish/work/csci400/materials"
    WENV_DEPS=('md')
    WENV_PROJECT='csci400'
    WENV_BRANCH='master'
    startup_wenv() { }
    shutdown_wenv() {
        unset -f slides_dev
    }
}

pkg_src() {
    name=$(pwd | rev | cut -f1 -d'-' | rev)
    cp -r src $name
    zip -r $name.zip $name
    rm -rf $name
}
