#!/bin/zsh

wenv_def() {
    WENV_DIR="/home/grish/work/research/resources/papers/other"
    WENV_DEPS=()
    WENV_PROJECT='pl-research-call'
    WENV_BRANCH=''
    startup_wenv() {
        foxitreader ./versum-annotated.pdf 2>&1 >/dev/null &
        clear
        kak versum_notes.md
    }
    shutdown_wenv() { }
}
