#!/bin/zsh

wenv_setup() {
    typeset -Ag WENV_CONSTS
    WENV_DIR="/home/grish/work/research/thesis/repo/proposal/presentation"
    WENV_DEPS=('md')
    WENV_NAME='proposal-presentation'
    WENV_BRANCH='master'
    wenv_init() {
        slides_dev 'presentation.md'
    }
    wenv_shutdown() { }
}
