#!/bin/zsh

wenv_def() {
    WENV_DIR="/home/grish/scratch/resume"
    WENV_DEPS=('md')
    WENV_PROJECT='resume'
    WENV_TASK=''
    WENV_BRANCH='dgrisham'
    startup_wenv() {
        pdf resume.pdf &
        wenv_tmux_layout devloop -w file resume.md 'make pdf'
        kak resume.md
    }
    shutdown_wenv() { }
}
