#!/bin/zsh

wenv_def() {
    WENV_DIR="$SCRATCH/rust-practice"
    WENV_DEPS=()
    # WENV_PROJECT="$WENV"

    startup_wenv() {
        wenv_tmux_layout 'devloop' 'make run'
        # wenv_tmux_split h 'w3m "file:///home/grish/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/doc/rust/html/book/index.html"'
        # tmux select-pane -L
        $EDITOR src/guess.rs
    }
    shutdown_wenv() {}
}
