#!/bin/zsh

wenv_def() {
    WENV_DIR="/home/grish/scratch/ipfs/research-bitswap/analysis"
    WENV_DEPS=('md')
    WENV_PROJECT=''
    WENV_TASK=73
    WENV_BRANCH='docs/strategy_analysis'
    startup_wenv() {
        doc_dev 'prelim_strategy_analysis.md' --number-sections
    }
    shutdown_wenv() { }
}
