#!/bin/zsh

wenv_def() {
    WENV_DIR="/home/grish/src/thesis"
    WENV_DEPS=()
    WENV_NAME='thesis'
    WENV_TASK=''
    WENV_EXTENSIONS=('edit')

    startup_wenv() {
        make
        pdf thesis.pdf &
        wenv_tmux_layout 'devloop' -w files bin/mkbase.sh template.tex sections/* figures/* -- make
        wenv_tmux_split -n 'tex' c 'edit tex'
        tmux select-window -t1
        edit -r doc
    }
    shutdown_wenv() { }
    bootstrap_wenv() {
        git clone git@github.com:dgrisham/thesis "$WENV_DIR"
    }
}

declare -Ag wenv_files=(
        ['build']='Makefile'
        ['tex']='{thesis,template}.tex'
        ['doc']='$(echo sections/* | xargs -n1 | sort -r)'
        ['base']='bin/mkbase.sh thesis.rst'
        ['todo']='todos.rst'
        ['rst']='{thesis.rst,sections/*}'
        ['all']='${wenv_files[rst]}'
)
