#!/bin/zsh

wenv_def() {
    WENV_DIR="/home/grish/downloads/torrents"
    WENV_DEPS=()
    WENV_PROJECT=''
    unset WENV_BRANCH
    WENV_TASK=''
    WENV_GITDIR=""

    startup_wenv() {
        tmux send-keys 'rtorrent' Enter
        wenv_tmux_split h
        tmux send-keys 'magnet '
    }
    shutdown_wenv() { }
}
