#!/bin/zsh

wenv_def() {
    WENV_DIR="/home/grish/downloads/torrents"
    # WENV_DEPS=('ipfs/ipfs')
    WENV_PROJECT=''
    unset WENV_BRANCH
    WENV_TASK=''
    WENV_EXTENSIONS=('c')

    startup_wenv() {
        tmux send-keys 'rtorrent' Enter
        wenv_tmux_split h
        tmux send-keys 'magnet '
    }
    shutdown_wenv() { }
}

declare -Ag wenv_dirs
wenv_dirs[library]="$MUSIC/library"
wenv_dirs[movies]="$MEDIA/videos/film"
wenv_dirs[media]="$MEDIA"
