#!/bin/zsh

wenv_setup() {
    WENV_DIR="/home/grish/scratch/ad-hoc-infra/terraform"
    WENV_DEPS=()
    WENV_PROJECT='ad-hoc-infra'
    WENV_BRANCH='master'
    WENV_TASK=''
    WENV_GITDIR=""

    wenv_bootstrap() {}
    wenv_init() {}
    wenv_shutdown() {}
}
