#!/bin/zsh

wenv_setup() {
    typeset -Ag WENV_CONSTS
    WENV_DIR=""
    WENV_DEPS=()
    WENV_NAME='analytical-strategy-analysis'
    WENV_BRANCH='master'
    WENV_TASK=''
    wenv_init() { }
    wenv_shutdown() { }
}
