#!/bin/zsh

wenv_setup() {
    WENV_DIR="$HOME/src/bitswap-diagram"
    WENV_DEPS=()
    WENV_PROJECT=''
    WENV_BRANCH='master'
    WENV_TASK=''
    WENV_GITDIR=""

    wenv_init() { }
    wenv_shutdown() { }
}
