#!/bin/zsh

wenv_setup() {
    WENV_DIR="/home/grish/scratch/bootstrap"
    WENV_DEPS=()
    WENV_PROJECT=''
    WENV_BRANCH=''
    WENV_TASK=''
    WENV_GITDIR=""

    wenv_init() {}
    wenv_shutdown() {}
}
