#!/bin/zsh

wenv_setup() {
    typeset -Ag WENV_CONSTS
    WENV_DIR="/home/grish/scratch/resume"
    WENV_DEPS=('md')
    WENV_NAME='cv'
    WENV_TASK=''
    WENV_BRANCH='dgrisham'
    wenv_init() {
        pdf cv.pdf &
        wenv_tmux_layout devloop -w file cv.md make
        kak cv.md
    }
    wenv_shutdown() { }
}
