#!/bin/zsh

# list
# ----
alias ll="ls -lh"
alias lr="ls -lrh"
alias la="ls -lAh"
alias lt="ls -lrth"
alias lta="ls -lrtAh"

# convenient cd
# -------------
chpwd() { ll }            # cd and ls
mc() { mv $@ && ${(P)#} } # mv and cd
cc() { cp $@ && ${(P)#} } # cp and cd

# compression
# -----------
alias tarx='tar -xvf'
tarc() { tar -cvf $1.tar $1 }
zipd() { zip -rv $1.zip $1 }

# Shortcuts
# =========

becho() { echo '\033[0;36m'$@'\033[0m' }
gecho() { echo '\033[0;32m'$@'\033[0m' }
recho() { echo '\033[0;31m'$@'\033[0m' }

loop() {
    local time=1
    while getopts ":t:h" opt; do
        case $opt in
            t)
                time="$OPTARG"
                ;;
        esac
    done
    shift $((OPTIND-1))
    while sleep "$time"; do clear; $@; done
}

alias usv='SVDIR=$USER_SVDIR sv'
alias tm="tmux attach"
alias kak='kak_session'
alias apv='mpv --vid=no'
alias ts='tabbed -c -r2 surf -e x -SN'
alias xc='xclip -selection c'
alias fd='/usr/bin/fd --hidden'
alias ag="/usr/local/bin/ag --color-path='1;36' --color-line-number='0;37' --color-match='1;33' --hidden --ignore node_modules --ignore .git"

# curl with status code
alias scurl='curl -w "%{http_code}"'

# sleep/hibernate
sys() {
    arg="$1"
    shift
    case $arg in
        disk|hibernate) echo "disk" | sudo tee /sys/power/state ;;
        mem|sleep)      echo "mem"  | sudo tee /sys/power/state ;;

    esac
}
_sys() {
    COMPREPLY=()
    complete +o default

    local word="${COMP_WORDS[COMP_CWORD]}"
    local prev="${COMP_WORDS[COMP_CWORD-1]}"

    if (( COMP_CWORD == 1 )); then
        local opts='disk hibernate mem sleep'
        COMPREPLY=( $(compgen -W "${opts}" -- ${word}) )
    fi
}
complete -F _sys sys 2>/dev/null

# git
# ---

alias gc='git commit -m'
alias gcm='git commit -m'
alias gca='git commit -a'
alias gcam='git commit -am'
alias gs='git status'
alias gl="git log --pretty=format:'%C(auto)%h %ad %C(green)%s%Creset %C(auto)%d [%an]' --graph --date=format:'%Y-%m-%d %H:%M' --all"
alias gde="git diff --name-only --diff-filter=U | uniq | xargs $EDITOR"
alias gco='git checkout'
alias gbr='git for-each-ref --sort=-committerdate refs/heads/ --format="%(HEAD) %(color:yellow)%(refname:short)%(color:reset) - %(color:red)%(objectname:short)%(color:reset) - %(contents:subject) - %(authorname) (%(color:green)%(committerdate:relative)%(color:reset))"'

gb() {
    git blame $@ | while read hash user date time tz lineno line; do
        gecho "\n$hash $user $date $time $tz $lineno"
        echo "$line"
        becho "$(git log -1 --pretty=%s $hash)"
    done
}

# open pdf as plaintext
# ---------------------
tdf() {
    lesspipe.sh "$1" | less
}

# $EDITOR <today's_date>.md
# -------------------------
edit_today() {
    local format='%Y-%m-%d'
    $EDITOR "`date +$format`.md"
}
alias et='edit_today'

edit_week() {
    local format='%Y-%m-%d'
    local which_monday='last-monday'
    [[ $(date +%a) == 'Mon' ]] && which_monday='this-monday'
    $EDITOR "`date -d$which_monday +$format`.md"
}
alias ew='edit_week'

# copy etc
# --------
cp_etc() {
    local dir="$1"
    [[ ! -d "$DOTFILES/etc/$dir" ]] && return 1
    for file in $(find "$DOTFILES/etc/$dir" -type f); do
        sudo cp "$file" "${file#$DOTFILES}"
    done
}

# Don't forget
# ------------
# cuesplit && cd split && for f in *.flac; do ffmpeg -i $f -ab 320k -map_metadata 0 -id3v2_version 3 "${f%.*}.mp3"; done && mkdir mp3 && mv *.mp3 mp3
