#!/usr/bin/zsh

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

zsh_dir="$HOME/dotfiles/zsh"
env_files=('profile' 'aliases')
for env_file in $env_files; do
    [[ -f "$zsh_dir/$env_file" ]] && source "$zsh_dir/$env_file"
done

source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
bindkey '^F' autosuggest-accept
ZSH_AUTOSUGGEST_ACCEPT_WIDGETS=(
    vi-end-of-line
)

export LSCOLORS='GaGxxxdxcxegedabagacad'

# necessary for WENVs
eval "$WENV_EXEC"
