#!/usr/bin/zsh

# Source Prezto.
if [[ -s "$SRC/zprezto/init.zsh" ]]; then
  source "$SRC/zprezto/init.zsh"
fi

# start mdpas (enabling via systemd not working)
# systemctl --user start mpdas

# zsh_dir="$HOME/dotfiles/zsh"
env_files=('profile' 'aliases')
for env_file in $env_files; do
    [[ -f "$ZDOTDIR/$env_file" ]] && source "$ZDOTDIR/$env_file"
done

export LS_COLORS="$LS_COLORS:di=01;36"

bindkey '^ ' autosuggest-accept
ZSH_AUTOSUGGEST_ACCEPT_WIDGETS=(
    vi-end-of-line
)

# Change cursor shape for different vi modes.
function zle-keymap-select {
    if [[ ${KEYMAP} == vicmd ]] ||
        [[ $1 = 'block' ]]; then
        echo -ne '\e[1 q'
    elif [[ ${KEYMAP} == main ]] ||
         [[ ${KEYMAP} == viins ]] ||
         [[ ${KEYMAP} = '' ]] ||
         [[ $1 = 'beam' ]]; then
       echo -ne '\e[5 q'
    fi
}
zle -N zle-keymap-select
zle-line-init() {
    zle -K viins # initiate `vi insert` as keymap (can be removed if `bindkey -V` has been set elsewhere)
    echo -ne "\e[5 q"
}
zle -N zle-line-init
echo -ne '\e[5 q' # Use beam shape cursor on startup.
preexec() { echo -ne '\e[5 q' ;} # Use beam shape cursor for each new prompt.

# necessary for WENVs
[[ -n "$WENV" ]] && wenv_exec "$WENV"
